import { Book } from '../lib/db';

export const books: Omit<Book, 'id'>[] = [
  {
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    isbn: '9780062416216',
    category: 'Fiction',
    status: 'available',
    location: 'Shelf A1',
    publishedYear: 1988,
    publisher: 'HarperOne',
    language: 'English',
    pages: 208,
    description: 'A novel about an Andalusian shepherd boy who dreams of finding a worldly treasure.',
    imageUrl: 'https://img.perlego.com/book-covers/598007/9780062416216_300_450.webp'
  },
  {
    title: 'Harry Potter Series (1-7 Bundle)',
    author: 'J.K. Rowling',
    isbn: '9780545162074',
    category: 'Fantasy',
    status: 'available',
    location: 'Shelf B2',
    publishedYear: 2007,
    publisher: 'Scholastic',
    language: 'English',
    pages: 4100,
    description: 'The complete collection of all seven Harry Potter novels.',
    imageUrl: 'https://www.curiosasociety.com/cdn/shop/products/HPBoxSet_Soft_Front.jpg?v=1571439832'
  },
  {
    title: 'The Art of War',
    author: 'Sun Tzu',
    isbn: '9780140439199',
    category: 'Non-Fiction',
    status: 'available',
    location: 'Shelf C3',
    publishedYear: -500,
    publisher: 'Penguin Classics',
    language: 'English',
    pages: 273,
    description: 'An ancient Chinese military treatise dating from the 5th century BC.',
    imageUrl: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1630683326i/10534.jpg'
  },
  {
    title: '1984',
    author: 'George Orwell',
    isbn: '9780451524935',
    category: 'Science Fiction',
    status: 'available',
    location: 'Shelf D4',
    publishedYear: 1949,
    publisher: 'Signet Classic',
    language: 'English',
    pages: 328,
    description: 'A dystopian social science fiction novel and cautionary tale.',
    imageUrl: 'https://archive.org/services/img/george-orwell-1984_202309/full/pct:200/0/default.jpg'
  },
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    isbn: '9780446310789',
    category: 'Fiction',
    status: 'available',
    location: 'Shelf E5',
    publishedYear: 1960,
    publisher: 'Grand Central Publishing',
    language: 'English',
    pages: 281,
    description: 'A classic novel about racial injustice and moral growth in the American South.',
    imageUrl: 'https://grey.com.np/cdn/shop/products/book-cover-To-Kill-a-Mockingbird-many-1961.webp?v=1669894816'
  },
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    isbn: '9780743273565',
    category: 'Fiction',
    status: 'available',
    location: 'Shelf F6',
    publishedYear: 1925,
    publisher: 'Scribner',
    language: 'English',
    pages: 180,
    description: 'A novel depicting the excesses of the Jazz Age.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg/960px-The_Great_Gatsby_Cover_1925_Retouched.jpg'
  },
  {
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    isbn: '9781585424337',
    category: 'Self-Help',
    status: 'available',
    location: 'Shelf G7',
    publishedYear: 1937,
    publisher: 'TarcherPerigee',
    language: 'English',
    pages: 320,
    description: 'A personal development and self-improvement book.',
    imageUrl: 'https://media.thuprai.com/__sized__/front_covers/think-and-grow-rich-f.jpg-thumbnail-280x405-70.jpg'
  },
  {
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    isbn: '9780062316097',
    category: 'Non-Fiction',
    status: 'available',
    location: 'Shelf H8',
    publishedYear: 2014,
    publisher: 'Harper',
    language: 'English',
    pages: 443,
    description: 'A book exploring the history of human evolution and civilization.',
    imageUrl: 'https://media.thuprai.com/products/Sapiens__A_Brief_History_of_Humankind.jpg'
  },
  {
    title: 'The Subtle Art of Not Giving a F*ck',
    author: 'Mark Manson',
    isbn: '9780062641540',
    category: 'Self-Help',
    status: 'available',
    location: 'Shelf I9',
    publishedYear: 2016,
    publisher: 'HarperOne',
    language: 'English',
    pages: 224,
    description: 'A self-help book that uses humor and profanity to discuss important life lessons.',
    imageUrl: 'https://booksmandala.com/_next/image?url=https%3A%2F%2Fbooks.bizmandala.com%2Fmedia%2Fbooks%2F9780062641540%2F9780062641540-9434.webp&w=3840&q=75'
  },
  {
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    isbn: '9780547928227',
    category: 'Fantasy',
    status: 'available',
    location: 'Shelf J10',
    publishedYear: 1937,
    publisher: 'Mariner Books',
    language: 'English',
    pages: 300,
    description: 'A fantasy novel about the adventures of Bilbo Baggins.',
    imageUrl: 'https://img1.od-cdn.com/ImageType-400/0293-1/%7BC9B54C84-0369-49C5-A0B3-98E3353A2129%7DIMG400.JPG'
  },
  {
    title: 'Salt, Fat, Acid, Heat',
    author: 'Samin Nosrat',
    isbn: '9781476753836',
    category: 'Cooking',
    status: 'available',
    location: 'Shelf K11',
    publishedYear: 2017,
    publisher: 'Simon & Schuster',
    language: 'English',
    pages: 480,
    description: 'A cookbook that teaches the four elements of good cooking.',
    imageUrl: 'https://images.penguinrandomhouse.com/cover/9780399582752'
  },
  {
    title: 'The Food Lab',
    author: 'J. Kenji López-Alt',
    isbn: '9780393081084',
    category: 'Cooking',
    status: 'available',
    location: 'Shelf L12',
    publishedYear: 2015,
    publisher: 'W. W. Norton & Company',
    language: 'English',
    pages: 958,
    description: 'A cookbook that explains the science behind cooking techniques.',
    imageUrl: 'https://m.media-amazon.com/images/I/515afUMn3aL.jpg'
  },
  {
    title: 'How to Cook Everything',
    author: 'Mark Bittman',
    isbn: '9780764578650',
    category: 'Cooking',
    status: 'available',
    location: 'Shelf M13',
    publishedYear: 2008,
    publisher: 'Wiley',
    language: 'English',
    pages: 1056,
    description: 'A comprehensive cookbook covering basic to advanced cooking techniques.',
    imageUrl: 'https://m.media-amazon.com/images/I/71-p1Bb9LvL._AC_UF1000,1000_QL80_.jpg'
  },
  {
    title: 'Plenty',
    author: 'Yotam Ottolenghi',
    isbn: '9781607747208',
    category: 'Cooking',
    status: 'available',
    location: 'Shelf N14',
    publishedYear: 2011,
    publisher: 'Chronicle Books',
    language: 'English',
    pages: 288,
    description: 'A vegetarian cookbook featuring Middle Eastern and Mediterranean recipes.',
    imageUrl: 'https://images.penguinrandomhouse.com/cover/9781607747208'
  },
  {
    title: 'Cocktail Codex',
    author: 'Alex Day, Nick Fauchald, David Kaplan',
    isbn: '9780399580949',
    category: 'Cooking',
    status: 'available',
    location: 'Shelf O15',
    publishedYear: 2018,
    publisher: 'Ten Speed Press',
    language: 'English',
    pages: 320,
    description: 'A book that breaks down cocktails into six basic templates.',
    imageUrl: 'https://images.penguinrandomhouse.com/cover/9780399580949'
  },
  {
    title: 'Half Baked Harvest Super Simple',
    author: 'Tieghan Gerard',
    isbn: '9780525577070',
    category: 'Cooking',
    status: 'available',
    location: 'Shelf P16',
    publishedYear: 2019,
    publisher: 'Clarkson Potter',
    language: 'English',
    pages: 320,
    description: 'A cookbook featuring easy, healthy recipes for busy people.',
    imageUrl: 'https://m.media-amazon.com/images/I/91ElCTiJSSL._AC_UF1000,1000_QL80_.jpg'
  },
  {
    title: 'The Beer Bible',
    author: 'Jeff Alworth',
    isbn: '9781607745259',
    category: 'Cooking',
    status: 'available',
    location: 'Shelf Q17',
    publishedYear: 2015,
    publisher: 'Workman Publishing',
    language: 'English',
    pages: 640,
    description: 'A comprehensive guide to beer styles, brewing, and tasting.',
    imageUrl: 'https://images.penguinrandomhouse.com/cover/9781607745259'
  },
  {
    title: 'The Flavor Bible',
    author: 'Karen Page, Andrew Dornenburg',
    isbn: '9780316118408',
    category: 'Cooking',
    status: 'available',
    location: 'Shelf R18',
    publishedYear: 2008,
    publisher: 'Little, Brown and Company',
    language: 'English',
    pages: 392,
    description: 'A guide to creative flavor combinations for chefs and home cooks.',
    imageUrl: 'https://images.penguinrandomhouse.com/cover/9780399578007'
  },
  {
    title: 'Mastering the Art of French Cooking',
    author: 'Julia Child, Louisette Bertholle, Simone Beck',
    isbn: '9780394721781',
    category: 'Cooking',
    status: 'available',
    location: 'Shelf S19',
    publishedYear: 1961,
    publisher: 'Knopf',
    language: 'English',
    pages: 752,
    description: 'A comprehensive guide to French cuisine.',
    imageUrl: 'https://images.penguinrandomhouse.com/cover/9781607747307'
  },
  {
    title: 'Cravings',
    author: 'Chrissy Teigen',
    isbn: '9781101903919',
    category: 'Cooking',
    status: 'available',
    location: 'Shelf T20',
    publishedYear: 2016,
    publisher: 'Clarkson Potter',
    language: 'English',
    pages: 240,
    description: 'A cookbook featuring favorite recipes from the author\'s kitchen.',
    imageUrl: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1489020472i/34515463.jpg'
  }
]; 